name: Update README

on:
  push:
    paths:
      - 'table_tennis.ipynb'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies & Convert README.ipynb
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
          jupyter nbconvert --to markdown table_tennis.ipynb

      - name: Rename markdown file
        run: mv table_tennis.md README.md

      - name: Commit changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update README from README.ipynb"
          git push https://$ACTIONS_TOKEN@github.com/nicofighter45/TableTennis.git
